M48
; DRILL file KiCad 10.0.0 date 2026-09-15T12:55:40
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-15T12:55:40+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X168.91Y-101.49
X168.91Y-110.49
T2
X124.46Y-101.6
X124.46Y-105.6
T3
X124.46Y-55.88
X124.46Y-110.49
X184.15Y-55.88
X184.15Y-110.49
M30
