// Code generated by MCHP Chatbot
#include "mcc_generated_files/system/system.h"
#include "utils.h"
//#include "tones.h"
#include "interrupts.h"


// IOC on falling edge
volatile enum _sw_status sw_status;
void Switch_Interrupt_Callback(void)
{
    // Update switch status flag    
    sw_status = PRESSED;

    // Reset the power-off timer by restarting Timer2
    pwr_status = ACTIVE;
    Timer2_CountCallBack = 0;
}

// Timer1 callback function. This will increment ms_ticks every millisecond.
void Timer1_Tick_Callback(void)
{
    ms_ticks++;
}


// Timer2 callback function. 
// We get here every 65.536ms, so for a 5 minute timeout, count to 5*60/0.065536 = 4578
volatile enum _pwr_status pwr_status;
volatile uint16_t Timer2_CountCallBack = 0;
void Timer2_Period_Callback(void)
{
    if( ++Timer2_CountCallBack >= TMR2_TIMEOUT_COUNT)
    {
        pwr_status = SHUTDOWN;
        Timer2_CountCallBack = 0;
    }
}
