#pragma once
#include "mcc_generated_files/system/system.h"

// Switch interrupt
// Code generated by MCHP Chatbot
enum _sw_status { OFF, PRESSED, PRESSED_SHORT, PRESSED_LONG };
extern volatile enum _sw_status sw_status;
void Switch_Interrupt_Callback(void);


// Millisecond timer interupt
extern volatile uint32_t ms_ticks;
void Timer1_Tick_Callback(void);


// Poweroff timer interrupt
// NOTE: These values assume a 65.536ms overflow rate, which was the maximum rate at XTAL_OSC=16MHz. 
//       At the current(?) 4MHz speed these are still valid but it would be "nice" if the preprocessor
//       calculates them like the tone frequencies.
#define TMR2_TIMEOUT_COUNT_5MIN     4578
#define TMR2_TIMEOUT_COUNT_2MIN     1831
#define TMR2_TIMEOUT_COUNT_1MIN     916
#define TMR2_TIMEOUT_COUNT_30SEC    457
#define TMR2_TIMEOUT_COUNT_10SEC    153
#define TMR2_TIMEOUT_COUNT          TMR2_TIMEOUT_COUNT_30SEC
enum _run_state { IDLE, INTRO, ACTIVE, SHUTDOWN, SHUTDOWN_INTRO };
extern volatile enum _run_state run_state;
extern volatile uint16_t Timer2_CountCallBack;
void Timer2_Period_Callback(void);

