// Code generated by MCHP Chatbot
#include "mcc_generated_files/system/system.h"
#include "utils.h"


//
// Variables
//
volatile uint32_t ms_ticks = 0;     // Free running millisecond counter. Needs to be 'volatile' since it's updated in an interrupt routine. Wraps around at ~49 days since it is just an uint32_t!


void delay_ms(uint16_t milliseconds)
{
    // Capture the tick count at the start of the delay
    uint32_t start_ticks = ms_ticks;
    
    // Wait until the difference matches the requested milliseconds
    while ((uint32_t)(ms_ticks - start_ticks) < milliseconds)
    {
        // Do nothing here, just wait until the time has elapsed
    }
}

// Try to seed the pseudo random number generator with a random value, taken from a floating analog input
void initRandomSeed(void)
{
    uint16_t adcResult;

    TRISAbits.TRISA4 = 1;       // RA4 input
    ANSELAbits.ANSA4 = 1;       // RA4 analog mode

    ADCON0 = 0b00001101;        // Select channel 3 (bit 6...2) and enable ADC (bit 0))
    ADCON0bits.GO_nDONE = 1;    // Start an analog-to-digital conversion

    while(ADCON0bits.GO_nDONE == 1);    // Wait for the conversion to end

    adcResult = (uint16_t)((ADRESH<<8) | ADRESL);   // Save the conversion value

    srand(adcResult);           // Use adc result to seed the random number generator

    ANSELAbits.ANSA4 = 0;       // RA0 digital mode
    TRISAbits.TRISA4 = 0;       // RA0 output
    ADON = 0;                   // Disable ADC
}

